### ISSUE TITLE
UI Components - Milestone 3

### ISSUE THREAD

**Issue by shirsho-12** [YeetAlone/orbital#42]
# Frontend 
For the first week of the next milestone, I will depend on you to create a lot of frontend components. I have planned out a lot of backend design overhauls for chats, calendar, and the map which will be very code-intensive. So I am putting out a list of components that need to be designed here.
- [ ] Find by department - drop-down menu
- [ ] ListTile component for the search
- [ ] When a department is clicked on the map, we should see a pop-up box with a list of people. The pop-up box and the list tiles there need to be designed
- [ ] Availability overlay. The colours I used there make it hard to see the text when you change the availability
- [ ] App Icon
- [ ] Chat text component
- [ ] Settings page for individual chats (a user should be able to delete a conversation, need a page to select that. Think Whatsapp when you click on a user's name)
- [ ] Dark theme colour selection. The current palate doesn't look very nice.
